[package]
name = "open-face-chinese-poker-full-house-hypothesis"
version = "0.1.0"
authors = ["Darren Tsung <darren@onesignal.com>"]
edition = "2018"

[dependencies]
structopt = "0.2.18"
rand = "0.7.0"
pbr = "1.0.1"
rayon = "1.1.0"
crossbeam-channel = "0.3.9"
antidote = "1.0.0"
